### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/m1-evaluacion-intermedia-anamontiaga#1]
Really cool job @anamontiaga !!!

Here you have some tips to improve the exercise:

## HTML
- [x] Fix the meta title of the page
- [x] Be extra careful with syntax, it looks like you have errors when closing <a/>
- [x] Should the `.menu` element be a nonsemantics `div` or a rich semantic `nav` (commonly used for our main navigation). 
- [x] The menu tag does not exist. We prefer to use another one. Which one?
- [x] We need a nav and a h1 tags
- [x] Menu items should be clickable
- [x] Humanize text in `alt` attributes
- [x] Remove HTML comments like `<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->`

## CSS - structure
- [x] Move the font CSS before your main CSS

## CSS - box model
- [x] Main section should fit 100% of browser's height
- [x] Block elements like our main one do not need a width: 100% or width: 100vw property to tell them to do what they are going to do anyway ;)
- [x] There are some weird margins, let's remove them: Remember the browser add some margins to the `<body>` element; and Any time we set an absolute or fixed position on an HTML element we should also set a left/right and a top/bottom CSS properties so it will display properly
- [x] Instead of adding extra space at the bottom of the header, you can make the menu links taller, that would make the header be tall enough and also would make the link easier to touch on mobile devices ;)
- [x] Your `main` element has some top padding, that's a solution to prevent the main title to disappear behind the fixed header but consider using min-height to do the trick ;)

## CSS - other
- [x] Avoid uppercase/capital on HTML texts, and `br` tag we can transform the text with CSS; this way we keep concepts separated, HTML for content, and CSS for styles
- [x] Finish the main title styles: words should jump and the typography is bolder

## Good practices
- [x] Try to use imperative for your commit messages. Ex. - > Fix central text

## Final remarks

Once you have these fixed try to finish the styles.
Start with the header and go step by step:

- add behavior styles: fix it to the window
- add structural styles: reset browser styles, center content (use whatever you feel more comfortable with: flex, text-align, margin auto...), add margin, padding...
- add cosmetic styles: color, background color...

Then repeat the same with main content.

## Call to action

Let me know if you have any doubts ;)

Go for it!!

**Comment by anamontiaga** [comment]
Thank you for the feedback! The improvements are implemented ;)

![bitmoji](https://render.bitstrips.com/v2/cpanel/359644fb-c5df-4412-9bc7-ae838696ef14-4321a1fa-69b2-4398-996b-3bc48c4dc787-v1.png?transparent=1&palette=1&width=246)

**Comment by migueldelmazo** [comment]
Gracias por hacer las mejoras que os hemos pedido!!!
